# Include KaaS GitLab CI library
include:
  - project: caas-ops/gitlabci-library
    ref: main
    file: main.yml

# Helm Chart is stored in the repository's root
variables:
  CI_DEBUG: 1

# Update Changelog and bump git tag
promote:
  stage: promote
  # Include only if a change was committed to the default branch AND if the repository contains a Chart.yaml, anywhere
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - "git version"
    - "semtag --version"
    - 'git config --global --add safe.directory "$CI_PROJECT_DIR"'
    - 'git config user.name "$CI_BOT_USER"'
    - 'git config user.email "$CI_BOT_EMAIL"'
  script:
    - 'git-chglog --next-tag "$CI_NEXT_TAG" --output "$CI_PROJECT_DIR"/CHANGELOG.md'
    - git add "$CI_PROJECT_DIR"/CHANGELOG.md
    - git diff --patch-with-stat --summary --staged
    - 'git commit -m "ci: promote to v$CI_NEXT_TAG"'
    - git tag "$CI_NEXT_TAG"
    - git push --atomic -o ci.skip "https://$CI_BOT_LOGIN:$CI_BOT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git" HEAD:"$CI_COMMIT_REF_NAME" "$CI_NEXT_TAG"
