fullnameOverride: cloudability-metrics-agent

imagePullPolicy: Always
imagePullSecrets:
  - name: dockerhub

clusterName: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
secretName: "cloudability-apikey"
