meshConfig:
  meshMTLS:
    minProtocolVersion: TLSV1_3
  rootNamespace: istio-system

global:
  istioNamespace: istio-system
  hub: gcr.io/istio-release
  defaultPodDisruptionBudget:
    enabled: false
  imagePullPolicy: "Always"
  priorityClassName: "system-cluster-critical"

  # Enable Datadog tracing
  proxy:
    tracer: "datadog"

pilot:
  # Autodiscovery of Datadog Metrics
  podAnnotations:
    ad.datadoghq.com/discovery.check_names: '["istio"]'
    ad.datadoghq.com/discovery.init_configs: "[{}]"
    ad.datadoghq.com/discovery.instances: |
      [
        {
          "istiod_endpoint": "http://%%host%%:15014/metrics",
          "use_openmetrics": "true"
        }
      ]

  autoscaleMin: 2
  autoscaleMax: 10

  # Resources for a pilot install - increased per SCTASK0403258
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi