nameOverride: "reloader"
fullnameOverride: "reloader"

reloader:
  reloadOnCreate: false
  reloadStrategy: annotations #Set to default, env-vars or annotations
  watchGlobally: true
  enableHA: true
  deployment:
    replicas: 3
    labels:
      tags.datadoghq.com/env: "qa"
      tags.datadoghq.com/service: "reloader"
      tags.datadoghq.com/version: "v1.0.22"
    image:
      pullPolicy: Always
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    livenessProbe:
      timeoutSeconds: 5
      failureThreshold: 5
      periodSeconds: 10
      successThreshold: 1
    readinessProbe:
      timeoutSeconds: 15
      failureThreshold: 5
      periodSeconds: 10
      successThreshold: 1
    resources:
      limits:
        cpu: "1000m"
        memory: "2000Mi"
      requests:
        cpu: "100m"
        memory: "512Mi"

    pod:
      annotations:
        ad.datadoghq.com/reloader.checks: |
          {
            "openmetrics": {
            "init_config": {},
            "instances": [
              {
                "openmetrics_endpoint": "http://%%host%%:9090/metrics",
                "namespace": "reloader",
                "metrics": ["reloader_reload_.*"]
              }
              ]
            }
          }

    
    service:
      port: 9090

    serviceAccount:
      name: reloader

    podDisruptionBudget:
      enabled: true
      # Set the minimum available replicas
      minAvailable: 1
