generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: dockerhub
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"index.docker.io":{"auth":"Y2hpbWVyYXNlcnZpY2VzOmhpZ2gtZGlyZWN0aW9uLU1BQ0hJTkUtQ0FSRS05MjE=","password":"high-direction-MACHINE-CARE-921","username":"chimeraservices"}}}

resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/aws-efs-csi-driver/helm-chart-aws-efs-csi-driver-2.2.6/deploy/kubernetes/base/controller-serviceaccount.yaml

patches:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: efs-csi-external-provisioner-role
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "list", "watch"]
