image:
  pullPolicy: Always
  pullSecrets:
    - dockerhub
priorityClassName: system-cluster-critical
resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 500Mi

## 2160h: 90 days
keyrenewperiod: 2160h
