image:
  pullPolicy: Always
  pullSecrets:
    - dockerhub
priorityClassName: system-cluster-critical
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 128m
    memory: 256Mi

## 2160h: 90 days
keyrenewperiod: 2160h
