apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-exporter
  namespace: cattle-system-exporter
spec:
  template:
    spec:
      serviceAccountName: rancher-exporter
      imagePullSecrets:
        - name: dockerhub
      containers:
        - imagePullPolicy: Always
          name: rancher-exporter
          image: virtualthoughts/prometheus-rancher-exporter:latest
