fullnameOverride: datadog

datadog:
  # Agent API key
  apiKeyExistingSecret: datadog-keys
  # APP key required for metrics
  appKeyExistingSecret: datadog-keys

  # ref. https://docs.datadoghq.com/getting_started/site
  #  site: datadoghq.eu

  # Set logging verbosity, valid log levels are: trace, debug, info, warn, error, critical, off
  logLevel: WARN

  # ref. https://github.com/DataDog/docker-dd-agent#tracing-from-the-host
  apm:
    # .Values.datadog.apm.enabled=true required to enable tracing port 8126 in datadog.datadog-system.svc.cluster.local
    enabled: true
    socketEnabled: true

  # Monitor Helm deployments
  helmCheck:
    enabled: true
    collectEvents: true

  # kubelet TLS verification for on-prem RKE
  kubelet:
    tlsVerify: false

  # Logs collection
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: true

  # Network Performance Monitoring - requires eBPF
  networkMonitoring:
    enabled: false

  # See https://www.datadoghq.com/blog/universal-service-monitoring-datadog
  # Universal Service Monitoring (USM) requires a Linux kernel version of 4.14.0 or higher. 
  # serviceMonitoring:
  #   enabled: true

  # Process Collection
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: false
    collectDNSStats: false

  # ref. https://docs.datadoghq.com/agent/kubernetes/prometheus/
  prometheusScrape:
    enabled: false
    serviceEndpoints: false
  # send select labels from namespace as labels
  namespaceLabelsAsTags:
    xcr_segment_name: segment
    xcr_team_name: team
    xcr_product_name: product
    xcr_env_name: env_name
    xcr_env: env

  # See https://www.datadoghq.com/blog/universal-service-monitoring-datadog
  serviceMonitoring:
    enabled: true

  securityAgent:
    # Cloud Security Posture Management (CSPM)
    compliance:
      enabled: false
    # Cloud Workload Security (CWS)
    runtime:
      enabled: false
      # Collection of CWS network events
      network:
        enabled: false

  ## https://help.datadoghq.com/hc/en-us/requests/1141411
  ## To enable namespace and pod labels to all kubernetes_state.* metrics.
  ## Upgrade is need for datadog to version 7.44.0 release.
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
     enabled: true
     labelsAsTags:
       namespace:
         xcr_segment_name: segment
         xcr_team_name: team
         xcr_product_name: product
         xcr_env_name: env_name
         xcr_env: env
       pod:
         xcr_service: service
         xcr_service_version: version

clusterAgent:
  image:
    pullPolicy: Always
  replicas: 2
  priorityClassName: system-cluster-critical
  createPodDisruptionBudget: true
  podAnnotations:
    sidecar.istio.io/inject: "false"

  # Enable the metricsProvider to be able to scale based on metrics in Datadog
  metricsProvider:
    enabled: false
    #will install DatadogMetrics CRD
    useDatadogMetrics: false

agents:
  image:
    pullPolicy: Always
  podAnnotations:
    sidecar.istio.io/inject: "false"
    ad.datadoghq.com/agent.logs: |
      [{
          "type": "file",
          "path": "/var/lib/rancher/rke/log/kubelet_*.log",
          "source": "kubelet_logs",
          "service": "kubelet_logs"
      },
      {
          "type": "file",
          "path": "/var/lib/rancher/rke/log/kube-proxy_*.log",
          "source": "kube_proxy_logs",
          "service": "kube_proxy_logs"
      },
      {
          "type": "file",
          "path": "/var/lib/rancher/rke/log/etcd_*.log",
          "source": "etcd_logs",
          "service": "etcd_logs"
      },
      {
          "type": "file",
          "path": "/var/lib/rancher/rke/log/kube-controller-manager_*.log",
          "source": "kube_controller_manager_logs",
          "service": "kube_controller_manager_logs"
      },
      {
          "type": "file",
          "path": "/var/lib/rancher/rke/log/kube-scheduler_*.log",
          "source": "kube_scheduler_logs",
          "service": "kube_scheduler_logs"
      }]
  volumes:
    - hostPath:
        path: /etc/kubernetes/ssl
      name: etcd-certs
    - hostPath:
        path: /var/lib/rancher/rke/log
      name: rke-kube-logs
  volumeMounts:
    - name: etcd-certs
      mountPath: /etc/kubernetes/ssl
      readOnly: true
    - name: rke-kube-logs
      mountPath: /var/lib/rancher/rke/log
      readOnly: true
  # podSecurity:
  #   capabilities:
  #     - SYS_ADMIN
  #     - SYS_RESOURCE
  #     - SYS_PTRACE
  #     - NET_ADMIN
  #     - NET_BROADCAST
  #     - NET_RAW
  #     - IPC_LOCK
  #     - CHOWN
  #     - AUDIT_CONTROL
  #     - DAC_READ_SEARCH
  tolerations:
    - key: node-role.kubernetes.io/controlplane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoExecute


