fullnameOverride: nginx

controller:
  image:
    pullPolicy: Always
  hostNetwork: true
  ingressClassResource:
    enabled: true
    default: true
  watchIngressWithoutClass: true
  publishService:
    enabled: false
  kind: DaemonSet
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false

defaultBackend:
  enabled: true
  image:
    pullPolicy: Always
