fullnameOverride: nginx

controller:
  image:
    pullPolicy: Always
  ingressClassResource:
    enabled: true
    default: true
  watchIngressWithoutClass: true
  publishService:
    enabled: false
  kind: DaemonSet
  priorityClassName: system-node-critical
  service:
    type: ClusterIP
  metrics:
    enabled: true

defaultBackend:
  enabled: true
  replicaCount: 2
  image:
    pullPolicy: Always
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 128m
      memory: 256Mi
