fullnameOverride: node-autoscaler
image:
  pullPolicy: Always
extraArgs:
  skip-nodes-with-local-storage: false
  logtostderr: true
  stderrthreshold: info
  v: 0
replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
# Disable pdb
podDisruptionBudget:
