fullnameOverride: cert-manager
global:
  podSecurityPolicy:
    useAppArmor: false
installCRDs: true
replicaCount: 2
image:
  pullPolicy: Always
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 128m
    memory: 256Mi
webhook:
  image:
    pullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 128m
      memory: 256Mi
cainjector:
  image:
    pullPolicy: Always
startupapicheck:
  image:
    pullPolicy: Always
ingressShim:
  defaultIssuerName: letsencrypt
  defaultIssuerKind: ClusterIssuer
  defaultACMEChallengeType: dns01
  defaultACMEDNS01ChallengeProvider: route53-cloud-platform
